/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.bitbyeteclub.c05.main;

import mx.com.bitbyeteclub.c03.adaptadores.AutoCompletaControlador;
import mx.com.bitbyeteclub.c03.adaptadores.AutoCompletaModeloVista;
import mx.com.bitbyeteclub.c03.adaptadores.AutoCompletaPresentador;
import mx.com.bitbyeteclub.c03.adaptadores.AutoCompletaVista;
import mx.com.bitbyeteclub.c04.vista.AutoCompleta;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author ELIALVA
 */
public class TestAutoCompletaUI extends javax.swing.JFrame implements AutoCompletaVista {

    @Autowired
    AutoCompletaPresentador autoCompletaPresentador;
    AutoCompletaControlador autoCompletaControlador;

    /**
     * Creates new form TestAutoCompletaUI
     */
    public TestAutoCompletaUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");
        jTextField1.setName("TSOambiente"); // NOI18N

        jTextField2.setText("jTextField1");
        jTextField2.setName("Bibliotecas Origen"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void sugiere(AutoCompletaModeloVista modeloVista) {
        System.out.println("Mostrando..." + modeloVista.getSugerencias());
    }

    public void inicia() {
        BuscaSugerencias bs = new BuscaSugerencias();
        AutoCompleta.instala(bs, jTextField1, jTextField2);
        setVisible(true);
        System.out.println("jTextField1.mdls " + jTextField1.getFont());
    }

    public static void main(String[] args) {
        TestAutoCompletaUI tacui = new TestAutoCompletaUI();
        tacui.inicia();
    }
}
